### ISSUE TITLE
2.10.14 of URLResolver

### ISSUE THREAD

**Issue by tknorris** [krazinabox/UFO-IPTV#1]
Why are you pushing versions of an addon you don't own? The current build for URLResolver is 2.10.13~beta6 but for some reason you have pushed it as 2.10.14. You don't even own URLResolver so you have no business doing this???

**Comment by krazinabox** [comment]
I have no idea what you are talking about? Just came back from vacation
last night.

**Comment by tknorris** [comment]
Your repo has 2.10.14 of URLRresolver in it...

**Comment by krazinabox** [comment]
Hmmm. Idk prolly one of my guys did it. I'm speaking to mk now. You could
address me nicer. Talk to me with respect. You will get a lot further that
way

**Comment by tknorris** [comment]
It's pretty disrespectful to push an addon that you don't own with a version number higher than the home repo of that addon...

**Comment by krazinabox** [comment]
Like I said, it wasn't me. I was away. I knew nothing about it. Im going to
remove it

**Comment by tknorris** [comment]
Thanks. I would appreciate it if you let the other devs that have commit access to your repo know that it's a big no-no to do that. Now if/when we push a real 2.10.14 of urlresolver we'll never be sure if they actually have the code from your repo or the real code.

Also, we are in the middle of a big beta test for urlresolver and all the people that have this repo are now not getting beta builds because they are stuck on 2.10.14.

I will have to push the best beta as 2.10.15~beta1 to get those people back on track.

**Comment by krazinabox** [comment]
I understand, my sincere apologies. I was unaware of this. Sorry for any
trouble it may have caused. I will remove it right away. Feel free to
message me anytime. Have a great week. Again my apologies.
